name: ktlint Formatting Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Download ktlint
        run: |
          curl -sSLOf https://github.com/pinterest/ktlint/releases/latest/download/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: |
          ktlint -F --reporter=plain?color=true --relative .
          ktlint --reporter=plain?color=true --relative .
